Repository waldreg/waldreg-client, pull requests merged in 2023-03, with the labels that each got.

#85 [Feat] 가입승인 임시구현
  src/App.tsx
  src/apis/authAPI.ts
  src/components/global/NavBar/index.tsx
  src/components/joiningpool/JoiningPoolUserInfo/index.tsx
  src/components/joiningpool/JoiningPoolUserList/index.tsx
  src/hooks/joiningpool/useUserList.tsx
  src/routes/JoiningPool/index.tsx
Labels: size/L

#87 Fix: 로그인 상태 인식 오류 수정
  src/states/auth-context.js
Labels: fix, size/XS

#90 [Feat] 네비게이션바 애니메이션
  src/components/Icons/BasicIcons.tsx
  src/components/global/NavBar/index.tsx
  src/components/global/NavBar/style.ts
  src/hooks/curuser/useCurUser.tsx
  src/states/auth-context.js
  src/types/userKeys.ts
Labels: design, feat, size/L

#97 [Feat] 상벌점 조회 페이지
  src/App.tsx
  src/components/global/NavBar/index.tsx
  src/components/reward/RewardUserList/index.tsx
  src/components/reward/UserCreateRewardModal/index.tsx
  src/components/user/UserReward/index.tsx
  src/hooks/reward/useCreateUserReward.tsx
  src/routes/Reward/index.tsx
Labels: feat, size/L

#99 [Fix] 게시판 카테고리 라우트 관련 오류
  src/components/board/BoardCategoryList/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/hooks/board/category/useBoardCategory.tsx
  src/hooks/board/useBoardList.tsx
  src/interfaces/board.ts
  src/routes/Board/BoardLayout/index.tsx
  src/routes/Board/BoardPage/index.tsx
  src/routes/Board/index.tsx
  src/routes/Setting/Board/index.tsx
  src/types/boardKey.ts
Labels: feat, fix, size/L

#101 [Design] 게시판 관련 css
  src/components/Icons/SettingIcons.tsx
  src/components/board/BoardCategory/index.tsx
  src/components/board/BoardCategoryList/index.tsx
  src/components/board/BoardCategoryList/style.ts
  src/components/board/BoardCommentCreate/style.ts
  src/components/board/BoardCommentList/index.tsx
  src/components/board/BoardCommentList/style.ts
  src/components/board/BoardCreate/style.ts
  src/components/board/BoardDetail/style.ts
  src/components/board/BoardList/style.ts
  src/components/common/PageTitle/style.ts
  src/components/global/Layout/index.tsx
  src/components/global/NavBar/index.tsx
  src/interfaces/board.ts
Labels: design, feat, size/L

#103 [Feat, Design] 홈페이지 조회, 수정, css
  src/App.tsx
  src/components/board/BoardCommentCreate/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardCreateButton/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/components/common/CreateButton/index.tsx
  src/components/common/button/index.tsx
  src/components/common/button/style.ts
  src/components/home/HomeUpdate/index.tsx
  src/components/home/HomeUpdate/style.ts
  src/hooks/home/useHome.tsx
  src/hooks/home/useHomeUpdate.tsx
  src/interfaces/home.ts
  src/routes/Board/BoardPage/index.tsx
  src/routes/Home/HomeLayout/index.tsx
  src/routes/Home/HomePage/index.tsx
  src/routes/Home/HomePage/style.ts
  src/routes/Home/index.tsx
  src/types/homeKeys.ts
Labels: design, feat, size/L

#104 [Feat, Design] 달력 기능, 형태 구현
  src/components/Icons/SettingIcons.tsx
  src/components/calendar/CalendarCells/index.tsx
  src/components/calendar/CalendarCells/style.ts
  src/components/calendar/CalendarDays/index.tsx
  src/components/calendar/CalendarDays/style.ts
  src/components/calendar/CalendarHeader/index.tsx
  src/components/calendar/CalendarHeader/style.ts
  src/components/calendar/CalendarModal/index.tsx
  src/components/calendar/CalendarModal/style.ts
  src/components/schedule/SeheduleCreate/index.tsx
  src/interfaces/schedule.ts
  src/routes/Schedule/Calendar/index.tsx
  src/routes/Schedule/Calendar/style.ts
  src/routes/Schedule/index.tsx
Labels: design, feat, size/XL

#105 [Refactor] 일정표 시작일, 종료일 추가
  package-lock.json
  package.json
  src/components/calendar/CalendarCells/index.tsx
  src/components/calendar/CalendarDatePicker/index.tsx
  src/components/calendar/CalendarDatePicker/style.ts
  src/components/calendar/CalendarModal/index.tsx
  src/components/calendar/CalendarModal/style.ts
  src/components/schedule/ScheduleDetail/index.tsx
  src/components/schedule/ScheduleList/index.tsx
  src/interfaces/schedule.ts
  src/routes/Schedule/Calendar/index.tsx
  src/routes/Schedule/Calendar/style.ts
  src/routes/Schedule/index.tsx
Labels: design, feat, refactor, size/L
