Repository waldreg/waldreg-client, pull requests merged in 2023-02, with the labels that each got.

#19 [Feat] 게시글 작성, 삭제 기능
  data/dummy.json
  package-lock.json
  package.json
  src/App.tsx
  src/apis/boardAPI.ts
  src/components/board/PostCreateButton/index.tsx
  src/components/board/PostCreateButton/style.ts
  src/components/board/PostDetail/index.tsx
  src/components/board/PostList/index.tsx
  src/components/board/PostList/style.ts
  src/components/common/CreateButton/index.tsx
  src/index.tsx
  src/interfaces/board.ts
  src/routes/Board/BoardCreate/index.tsx
  src/routes/Board/BoardDetail/index.tsx
  src/routes/Board/BoardDetail/style.ts
  src/routes/Board/BoardList/index.tsx
  src/routes/Board/BoardList/style.ts
  src/routes/Board/BoardUpdate/index.tsx
  src/states/board.ts
Labels: feat, size/L

#20 [Feat] 역할 CRUD
  src/App.tsx
  src/apis/axios.ts
  src/apis/characterAPI.ts
  src/apis/userAPI.ts
  src/components/common/checkbox/check.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/common/inputs/input_add.tsx
  src/hooks/useCheckBox.tsx
  src/hooks/useInput.tsx
  src/interfaces/basic.ts
  src/interfaces/character.ts
  src/routes/Setting/Character/index.tsx
  src/routes/Setting/index.tsx
  src/types/settingKeys.ts
Labels: feat

#24 [Refactor] Board, Category custom hook 리팩토링
  data/dummy.json
  src/apis/boardAPI.ts
  src/components/board/PostDetail/index.tsx
  src/components/board/PostList/index.tsx
  src/components/board/PostTitleInput/index.tsx
  src/components/board/PostTitleInput/style.ts
  src/components/common/CreateButton/index.tsx
  src/components/common/CreateButton/style.ts
  src/hooks/board/useCreatePost.tsx
  src/hooks/board/useDeletePost.tsx
  src/hooks/board/usePost.tsx
  src/hooks/board/usePostList.tsx
  src/hooks/category/useBoardCategories.tsx
  src/routes/Board/BoardCreate/index.tsx
  src/routes/Board/BoardDetail/index.tsx
  src/routes/Board/BoardList/index.tsx
  src/routes/Board/BoardList/style.ts
  src/routes/Home/index.tsx
Labels: refactor, size/L

#27 Refactor/#21
  src/App.tsx
  src/apis/characterAPI.ts
  src/components/Icons/BasicIcons.tsx
  src/components/Icons/LogoIcons.tsx
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/character/CharacterUser/index.tsx
  src/components/common/buttons/button_big.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/common/inputs/input_add.tsx
  src/components/common/toggles/toggle.tsx
  src/components/global/Layout/index.tsx
  src/components/global/NavBar/index.tsx
  src/hooks/common/useCheckBox.tsx
  src/hooks/common/useInput.tsx
  src/hooks/common/useToggle.tsx
  src/hooks/useCharQuery.ts
  src/index.css
  src/index.tsx
  src/routes/Setting/Character/index.tsx
  src/routes/Setting/index.tsx
  src/styles/GlobalStyle.tsx
Labels: refactor

#29 Fix/#28
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/constants/color.ts
  src/constants/fonts.ts
  src/constants/fonts.tsx
Labels: help wanted, fix

#34 [Refactor] board apis와 custom hooks 합치기
  src/apis/boardAPI.ts
  src/apis/categoryAPI.ts
  src/hooks/board/useBoardDetail.tsx
  src/hooks/board/useBoardList.tsx
  src/hooks/board/useCreateBoard.tsx
  src/hooks/board/useDeleteBoard.tsx
  src/hooks/category/useBoardCategories.tsx
  src/types/boardKey.ts
Labels: refactor, size/L

#38 [Feat] 일정 생성, 삭제, 조회
  src/App.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardList/index.tsx
  src/components/category/BoardCategory/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/schedule/ScheduleDetail/index.tsx
  src/components/schedule/ScheduleList/index.tsx
  src/components/schedule/SeheduleCreate/index.tsx
  src/hooks/board/useBoardCreate.tsx
  src/hooks/board/useBoardDelete.tsx
  src/hooks/board/useBoardDetail.tsx
  src/hooks/schedule/useScheduleCreate.tsx
  src/hooks/schedule/useScheduleDelete.tsx
  src/hooks/schedule/useScheduleDetail.tsx
  src/hooks/schedule/useScheduleList.tsx
  src/hooks/schedule/useScheduleUpdate.tsx
  src/interfaces/schedule.ts
  src/routes/Schedule/Calendar/index.tsx
  src/routes/Schedule/index.tsx
  src/types/scheduleKye.ts
Labels: feat, refactor, size/L

#40 [Feat] 게시판 생성, 카테고리 생성, 조회, 삭제
  src/components/Icons/BoardIcons.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardCreate/style.ts
  src/components/board/BoardCreateButton/index.tsx
  src/components/board/BoardList/index.tsx
  src/components/common/CreateButton/index.tsx
  src/constants/color.ts
  src/hooks/board/useBoardCreate.tsx
  src/hooks/board/useBoardDelete.tsx
  src/hooks/board/useBoardDetail.tsx
  src/hooks/board/useBoardList.tsx
  src/hooks/category/useBoardCategoryCreate.tsx
  src/hooks/category/useBoardCategoryDelete.tsx
  src/hooks/category/useBoardCategoryList.tsx
  src/interfaces/board.ts
  src/interfaces/category.ts
  src/routes/Board/Announcement/AnnouncementLayout/index.tsx
  src/routes/Board/Announcement/AnnouncementLayout/style.ts
  src/routes/Board/Announcement/index.tsx
  src/routes/Board/Announcement/style.ts
  src/routes/Board/Bug/index.tsx
  src/routes/Board/Changelog/index.tsx
  src/routes/Board/Free/index.tsx
  src/routes/Board/Question/index.tsx
  src/routes/Board/index.tsx
  src/states/board.ts
  src/types/boardKey.ts
  src/types/settingKeys.ts
Labels: design, feat, refactor, size/L

#42 [Refactor] 역할관리 CRUD
  src/apis/characterAPI.ts
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/character/Permission/index.tsx
  src/components/common/toggles/toggle.tsx
  src/hooks/character/useCharacter.tsx
  src/hooks/character/useCharacterList.tsx
  src/hooks/character/useCreateCharacter.tsx
  src/hooks/character/useDeleteCharacter.tsx
  src/hooks/character/useEditCharacter.tsx
  src/hooks/character/usePermissionList.tsx
  src/hooks/common/useCheckBox.tsx
  src/hooks/common/useInput.tsx
  src/hooks/common/useToggle.tsx
  src/hooks/useCharQuery.ts
  src/routes/Setting/Character/index.tsx
Labels: feat, refactor, size/XL

#44 [Feat] 유저 관리 CRUD
  src/apis/userAPI.ts
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/character/Permission/index.tsx
  src/components/common/checkbox/check.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/global/NavBar/index.tsx
  src/hooks/character/useCharacterList.tsx
  src/hooks/character/useCreateCharacter.tsx
  src/hooks/character/useEditCharacter.tsx
  src/hooks/character/usePermissionList.tsx
  src/hooks/user/useEditUserCharacter.tsx
  src/hooks/user/useKickUser.tsx
  src/hooks/user/useUser.tsx
  src/hooks/user/useUserList.tsx
  src/interfaces/character.ts
  src/interfaces/user.ts
  src/routes/Setting/Character/index.tsx
  src/routes/Setting/User/index.tsx
  src/routes/Setting/index.tsx
  src/types/settingKeys.ts
  src/types/userKeys.ts
Labels: feat, size/L

#46 [Fix] Character 중복 네이밍 수정
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/character/Permission/index.tsx
  src/hooks/character/useCharacter.tsx
  src/routes/Setting/Character/index.tsx
  src/routes/Setting/index.tsx
Labels: fix, size/M

#47 Design/#31
  src/components/Icons/BoardIcons.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardCreate/style.ts
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardDetail/style.ts
  src/components/board/BoardList/index.tsx
  src/components/board/BoardList/style.ts
Labels: size/L

#49 [Fix] 게시판 setState 오류 해결
  src/routes/Board/Announcement/index.tsx
  src/routes/Board/Bug/index.tsx
  src/routes/Board/Changelog/index.tsx
  src/routes/Board/Free/index.tsx
  src/routes/Board/Question/index.tsx
Labels: fix, size/S

#51 [Refactor] 설정 페이지 > 게시판 관리 기능
  src/components/board/BoardCategory/index.tsx
  src/components/board/BoardCategory/style.ts
  src/components/board/BoardCategoryList/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/global/NavBar/index.tsx
  src/hooks/board/useBoardCategoryCreate.tsx
  src/hooks/board/useBoardCategoryDelete.tsx
  src/hooks/board/useBoardCategoryList.tsx
  src/hooks/board/useBoardCreate.tsx
  src/hooks/category/useBoardCategoryCreate.tsx
  src/interfaces/board.ts
  src/routes/Board/BoardLayout/index.tsx
  src/routes/Board/BoardLayout/style.ts
  src/routes/Board/BoardPage/index.tsx
  src/routes/Board/BoardPage/style.ts
  src/routes/Board/Bug/index.tsx
  src/routes/Board/Changelog/index.tsx
  src/routes/Board/Free/index.tsx
  src/routes/Board/Question/index.tsx
  src/routes/Board/index.tsx
  src/routes/Setting/Board/index.tsx
  src/routes/Setting/index.tsx
Labels: refactor, size/L

#52 [Feat] 로그인/회원가입 기본 틀
  package-lock.json
  package.json
  src/App.tsx
  src/apis/axios.ts
  src/components/auth/login/index.js
  src/components/auth/signup/index.js
  src/components/global/NavBar/index.tsx
  src/index.tsx
  src/routes/Auth/Login/index.tsx
  src/states/auth-context.js
Labels: size/L

#55 [Feat] 상벌점 태그 CRUD
  src/components/global/NavBar/index.tsx
  src/hooks/reward/useCreateRewardTag.tsx
  src/hooks/reward/useDeleteRewardTag.tsx
  src/hooks/reward/useEditRewardTag.tsx
  src/hooks/reward/useRewardTags.tsx
  src/interfaces/reward.ts
  src/routes/Reward/index.tsx
  src/routes/Setting/Reward/index.tsx
  src/routes/Setting/index.tsx
  src/types/rewardKeys.ts
Labels: feat, size/L

#60 [Feat] 게시판 수정, 게시판 카테고리 수정 기능 추가
  src/components/Icons/SettingIcons.tsx
  src/components/board/BoardCategoryList/index.tsx
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  src/hooks/board/useBoardCategoryUpdate.tsx
  src/hooks/board/useBoardUpdate.tsx
  src/routes/Board/BoardPage/index.tsx
  src/routes/Board/index.tsx
  src/routes/Setting/Board/index.tsx
Labels: feat, size/L

#62 [Feat] 네비게이션 디자인 수정
  src/components/Icons/BasicIcons.tsx
  src/components/global/NavBar/index.tsx
Labels: design, size/L

#63 [Refactor, Design] NavBar 관련 게시판 카테고리
  src/components/board/BoardCategory/index.tsx
  src/components/board/BoardCategory/style.ts
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardList/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/global/NavBar/style.ts
  src/routes/Board/BoardPage/index.tsx
  src/routes/Board/index.tsx
Labels: design, refactor, size/L

#65 [Feature] 게시판 댓글 CRUD
  package-lock.json
  package.json
  src/components/board/BoardCategory/index.tsx
  src/components/board/BoardCategoryList/index.tsx
  src/components/global/NavBar/index.tsx
  src/hooks/board/category/useBoardCategoryCreate.tsx
  src/hooks/board/category/useBoardCategoryDelete.tsx
  src/hooks/board/category/useBoardCategoryList.tsx
  src/hooks/board/category/useBoardCategoryUpdate.tsx
  src/hooks/board/comment/useCommentCreate.tsx
  src/hooks/board/comment/useCommentDelete.tsx
  src/hooks/board/comment/useCommentList.tsx
  src/hooks/board/comment/useCommentUpdate.tsx
  src/interfaces/board.ts
  src/routes/Setting/Board/index.tsx
  src/types/boardKey.ts
Labels: feat, size/L

#68 [Design, Feat] 댓글 컴포넌트 생성
  src/components/Icons/BoardIcons.tsx
  src/components/board/BoardCommentCreate/index.tsx
  src/components/board/BoardCommentCreate/style.ts
  src/components/board/BoardCommentList/index.tsx
  src/components/board/BoardCommentList/style.ts
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardDetail/style.ts
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/common/CreateButton/index.tsx
  src/components/common/CreateButton/style.ts
  src/hooks/board/comment/useCommentCreate.tsx
  src/hooks/board/comment/useCommentDelete.tsx
  src/interfaces/board.ts
  src/styles/GlobalStyle.tsx
Labels: design, feat, size/L

#73 [Fix] 경로 오류 수정
  src/components/board/BoardCommentCreate/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/constants/fonts.ts
  tsconfig.json
Labels: fix, size/M

#75 [Design] 역할 관리 페이지
  src/components/Icons/BasicIcons.tsx
  src/components/character/CharacterCreateModal/index.tsx
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterList/style.ts
  src/components/character/CharacterSetting/index.tsx
  src/components/character/CharacterUser/index.tsx
  src/components/character/Permission/index.tsx
  src/components/common/buttons/button_big.tsx
  src/components/common/checkbox/check.tsx
  src/components/common/checkbox/checkbox.tsx
  src/components/common/inputs/input_fill.tsx
  src/components/common/inputs/input_line.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  src/components/global/Layout/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/global/NavBar/style.ts
  src/components/global/TopBar/index.tsx
  src/constants/fonts.ts
  src/interfaces/basic.ts
  src/routes/Setting/Board/index.tsx
  src/routes/Setting/Character/index.tsx
  src/routes/Setting/Reward/index.tsx
Labels: design, refactor, size/XL

#76 [Refactor, Design] Signup,Login refactoring 및 css
  src/App.tsx
  src/apis/authAPI.ts
  src/apis/axios.ts
  src/components/auth/login/LoginForm/index.tsx
  src/components/auth/login/LoginForm/style.ts
  src/components/auth/login/index.js
  src/components/auth/signup/SignupForm/index.tsx
  src/components/auth/signup/SignupForm/style.ts
  src/components/auth/signup/SignupFormDataProvider/index.tsx
  src/components/auth/signup/index.js
  src/components/common/authforminput/index.tsx
  src/components/common/authforminput/style.ts
  src/components/common/errormessage/index.tsx
  src/components/common/errormessage/style.ts
  src/components/global/NavBar/index.tsx
  src/constants/fonts.ts
  src/hooks/signup/useSignupFormData.tsx
  src/types/auth.ts
  src/utils/getErrorMessage.ts
  src/utils/regex.ts
Labels: design, refactor, size/XL

#81 [Fix] 게시판 오류 수정, 파일 데이터 서버에 보내기
  src/components/board/BoardCommentList/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardFileUpload/index.tsx
  src/components/board/BoardFileUpload/style.ts
  src/components/board/BoardList/index.tsx
  src/components/board/BoardList/style.ts
  src/components/board/BoardUpdate/index.tsx
  src/interfaces/board.ts
  src/routes/Setting/Board/index.tsx
Labels: bug, feat, fix, size/L
