Repository waldreg/waldreg-client, pull requests merged in 2023-06, with the labels that each got.

#130 [Fix] 회원가입 에러핸들링
  src/components/auth/signup/SignupForm/index.tsx
  src/utils/getErrorMessage.ts
  src/utils/regex.ts
Labels: fix, size/M

#133 [Feat] 파일, 이미지 다운로드
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardFileUpload/index.tsx
  src/components/board/BoardFileUpload/style.ts
  src/components/board/BoardUpdate/index.tsx
  src/hooks/common/useCheckBox.tsx
  src/hooks/user/useAllUserList.tsx
  src/interfaces/board.ts
  src/routes/Board/BoardDetail/index.tsx
Labels: feat, fix, size/L

#134 [Feat] 에러핸들링 구축
  public/pictogram/warning.png
  src/App.tsx
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterSetting/index.tsx
  src/components/character/CharacterUser/index.tsx
  src/components/common/container/index.tsx
  src/components/common/errormodal/index.tsx
  src/components/common/globalModal/index.tsx
  src/components/common/inputs/input_line.tsx
  src/constants/error.ts
  src/hooks/character/useCharacter.tsx
  src/hooks/character/useCharacterList.tsx
  src/hooks/character/useCreateCharacter.tsx
  src/hooks/character/useDeleteCharacter.tsx
  src/hooks/character/useEditCharacter.tsx
  src/hooks/character/usePermissionList.tsx
  src/hooks/common/useModal.tsx
  src/hooks/error/useApiError.tsx
  src/index.tsx
  src/routes/Reward/index.tsx
  src/types/modal.ts
Labels: feat, size/L

#139 [Fix] 홈페이지 공지글 수정 에러 핸들링
  src/App.tsx
  src/components/auth/login/LoginForm/index.tsx
  src/components/common/createbutton/index.tsx
  src/components/global/Layout/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/home/HomeUpdate/index.tsx
  src/components/home/HomeUpdate/style.ts
  src/routes/Home/HomePage/index.tsx
Labels: size/M

#141 [Fix] 게시판 QueryKey 오류
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/hooks/board/category/useBoardCategoryCreate.tsx
  src/hooks/board/category/useBoardCategoryDelete.tsx
  src/hooks/board/useBoardCreate.tsx
  src/hooks/board/useBoardDelete.tsx
  src/hooks/board/useBoardUpdate.tsx
  src/routes/Board/BoardDetail/index.tsx
Labels: bug, size/M

#145 [Design] 게시글 검색 border 수정
  src/routes/Board/BoardSearch/style.ts
Labels: design, size/S
