Repository waldreg/waldreg-client, pull requests merged in 2023-05, with the labels that each got.

#108 [Fix] 일정 수정, 삭제 기능 버그
  src/components/Icons/CalendarIcons.tsx
  src/components/Icons/SettingIcons.tsx
  src/components/calendar/CalendarCells/index.tsx
  src/components/calendar/CalendarDatePicker/index.tsx
  src/components/calendar/CalendarModal/index.tsx
  src/hooks/schedule/useScheduleUpdate.tsx
  src/routes/Schedule/Calendar/index.tsx
  src/routes/Schedule/Calendar/style.ts
Labels: bug, size/L

#110 [Feat] 설정 관련 리팩토링
  package-lock.json
  package.json
  src/components/character/CharacterSetting/index.tsx
  src/components/character/CharacterUser/index.tsx
  src/components/character/UserCreateCharacterModal/index.tsx
  src/components/common/checkbox/check.tsx
  src/components/reward/ResetRewardModal/index.tsx
  src/components/reward/RewardReset/index.tsx
  src/components/reward/RewardTagDeleteModal/index.tsx
  src/components/reward/RewardTagList/index.tsx
  src/components/reward/RewardUser/index.tsx
  src/components/reward/RewardUserList/index.tsx
  src/components/reward/UserCreateRewardModal/index.tsx
  src/components/user/UserInfo/index.tsx
  src/components/user/UserItems/index.tsx
  src/components/user/UserList/index.tsx
  src/components/user/UserReward/index.tsx
  src/hooks/reward/useDeleteUserReward.tsx
  src/hooks/user/useUserList.tsx
  src/types/userKeys.ts
Labels: feat, refactor, size/XL

#113 [Feat] 게시판, 게시판 설정, navbar
  src/components/Icons/BasicIcons.tsx
  src/components/Icons/BoardIcons.tsx
  src/components/Icons/SettingIcons.tsx
  src/components/auth/login/LoginForm/index.tsx
  src/components/auth/signup/SignupForm/index.tsx
  src/components/board/BoardCategory/index.tsx
  src/components/board/BoardCategoryList/index.tsx
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardCreate/style.ts
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardFileUpload/index.tsx
  src/components/board/BoardFileUpload/style.ts
  src/components/board/BoardList/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/components/calendar/CalendarCells/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/global/NavBar/style.ts
  src/components/home/HomeUpdate/index.tsx
  src/components/home/HomeUpdate/style.ts
  src/routes/Home/HomePage/index.tsx
  src/routes/Home/HomePage/style.ts
  src/routes/Setting/Board/index.tsx
  src/routes/Setting/Board/style.ts
  src/states/auth-context.js
  src/states/board.ts
Labels: bug, design, feat, fix, size/L

#116 [Feat] 게시판 유저에 따라 수정
  src/components/board/BoardCommentCreate/index.tsx
  src/components/board/BoardCommentCreate/style.ts
  src/components/board/BoardCommentList/index.tsx
  src/components/board/BoardCommentList/style.ts
  src/components/board/BoardDetail/index.tsx
  src/components/board/BoardDetail/style.ts
  src/components/global/Layout/index.tsx
  src/hooks/board/comment/useCommentUpdate.tsx
  src/routes/Board/BoardLayout/style.ts
  src/routes/Board/BoardPage/index.tsx
Labels: design, feat, size/L

#118 [Design] motion 추가
  package-lock.json
  package.json
  src/components/Icons/BasicIcons.tsx
  src/components/character/CharacterList/index.tsx
  src/components/character/CharacterList/style.ts
  src/components/character/CharacterSetting/index.tsx
  src/components/character/CharacterUser/index.tsx
  src/components/common/button/index.tsx
  src/components/common/checkbox/check.tsx
  src/components/common/container/index.tsx
  src/components/common/inputs/input_fill.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  src/components/common/toggles/toggle.tsx
  src/components/global/Layout/index.tsx
  src/components/global/NavBar/index.tsx
  src/components/global/NavBar/style.ts
  src/components/reward/RewardTagList/index.tsx
  src/components/reward/RewardUser/index.tsx
  src/components/reward/RewardUserList/index.tsx
  src/components/reward/UserCreateRewardModal/index.tsx
  src/components/user/UserList/index.tsx
  src/components/user/UserSetting/index.tsx
  src/constants/animation.ts
  src/routes/Reward/index.tsx
  src/routes/Setting/Reward/index.tsx
  src/styles/GlobalStyle.tsx
Labels: design, feat, size/XL

#121 [Docs] Git 폴더명 변경
  src/components/common/createbutton/index.tsx
  src/components/common/createbutton/style.ts
  src/components/common/pagetitle/index.tsx
  src/components/common/pagetitle/style.ts
Labels: size/XS, docs

#125 [Design] motion 추가
  src/components/board/BoardCreate/index.tsx
  src/components/board/BoardUpdate/index.tsx
  src/components/common/container/index.tsx
  src/routes/Board/BoardDetail/index.tsx
  src/routes/Board/BoardDetail/style.ts
  src/routes/Board/BoardPage/index.tsx
  src/routes/Board/BoardPage/style.ts
  src/routes/Board/index.tsx
  src/routes/Home/HomePage/index.tsx
  src/routes/Home/HomePage/style.ts
  src/routes/Schedule/Calendar/index.tsx
  src/routes/Schedule/Calendar/style.ts
  src/routes/Setting/Board/index.tsx
  src/routes/Setting/Board/style.ts
Labels: design, size/L
